# MASTER ESPHome Configuration for Fairland/Inverpad on LilyGO T-CAN485 board

substitutions:
  name_prefix: Pool Heat Pump

esphome:
  on_boot:
    then:
      - output.turn_on: bus_power
      - output.turn_on: RS485_EN
      - output.turn_on: RS485_SE

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

logger:
  level: INFO
  hardware_uart: UART0

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO4
    num_leds: 1
    chipset: ws2812
    name: "RGB Indicator"

output:
  - platform: gpio
    pin: GPIO17
    id: RS485_EN
  - platform: gpio
    pin: GPIO19
    id: RS485_SE
  - platform: gpio
    pin: GPIO16
    id: bus_power

uart:
  rx_pin: GPIO21
  tx_pin: GPIO22
  baud_rate: 9600
  id: u_modbus

modbus:
  uart_id: u_modbus
  id: c_modbus

modbus_controller:
  - id: heatpump
    address: 1
    modbus_id: c_modbus
    update_interval: 5s

switch:
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Power"
    id: hp_power
    register_type: coil
    address: 0
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Manual Defrost"
    register_type: coil
    address: 1
    disabled_by_default: true

select:
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Operating Mode"
    id: hp_operating_mode
    address: 0
    value_type: U_WORD
    optionsmap:
      'Auto': 0
      'Heating': 1
      'Cooling': 2

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Power Mode"
    id: hp_power_mode
    address: 1
    value_type: U_WORD
    optionsmap:
      'Normal': 0
      'Silence': 1
      'Super Silence': 2
      'Turbo': 3

number:
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Target Temp (Auto)"
    id: hp_target_auto
    address: 2
    value_type: U_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    min_value: 18
    max_value: 40
    lambda: "return (x - 60)/2;"
    write_lambda: "return ((x * 2) + 60);"

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Target Temp (Heating)"
    id: hp_target_heating
    address: 3
    value_type: U_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    min_value: 18
    max_value: 40
    lambda: "return (x - 60)/2;"
    write_lambda: "return ((x * 2) + 60);"

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Target Temp (Cooling)"
    id: hp_target_cooling
    address: 4
    value_type: U_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    min_value: 18
    max_value: 40
    lambda: "return (x - 60)/2;"
    write_lambda: "return ((x * 2) + 60);"

sensor:
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Compressor Speed"
    unit_of_measurement: '%'
    register_type: read
    address: 0
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} PFC Voltage"
    id: pool_heatpump_pfc_V
    unit_of_measurement: 'V'
    register_type: read
    address: 2
    value_type: U_WORD
    device_class: voltage
    entity_category: diagnostic

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Water Inlet Temperature"
    id: pool_water_temp
    unit_of_measurement: '°C'
    register_type: read
    address: 3
    value_type: U_WORD
    device_class: temperature
    filters:
      - offset: -60
      - multiply: 0.5
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Water Outlet Temperature"
    unit_of_measurement: '°C'
    register_type: read
    address: 4
    value_type: U_WORD
    device_class: temperature
    filters:
      - offset: -60
      - multiply: 0.5
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Ambient Temperature"
    unit_of_measurement: '°C'
    register_type: read
    address: 5
    value_type: U_WORD
    device_class: temperature
    filters:
      - offset: -60
      - multiply: 0.5
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Gas Exhaust Temperature"
    unit_of_measurement: '°C'
    register_type: read
    address: 6
    value_type: U_WORD
    device_class: temperature
    filters:
      - offset: -60
      - multiply: 0.5
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Evaporator Coil Pipe Temp"
    unit_of_measurement: '°C'
    register_type: read
    address: 7
    value_type: U_WORD
    device_class: temperature
    filters:
      - offset: -60
      - multiply: 0.5
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Compressor Current"
    id: pool_heatpump_pfc_A
    unit_of_measurement: 'A'
    register_type: read
    address: 11
    value_type: U_WORD
    device_class: current
    filters:
      - multiply: 0.1
    accuracy_decimals: 1

  - platform: template
    name: "${name_prefix} Power Consumption"
    id: pool_heatpump_power
    device_class: power
    unit_of_measurement: 'W'
    lambda: |-
      if (id(pool_heatpump_pfc_A).state) {
      return id(pool_heatpump_pfc_A).state * id(pool_heatpump_pfc_V).state;
      } else {
      return 0.0;
      }    
    update_interval: 5s

binary_sensor:
  - platform: status
    name: "${name_prefix} Online Status"

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Power Status"
    register_type: discrete_input
    address: 0
    device_class: power

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Fault Error"
    register_type: discrete_input
    address: 16
    device_class: problem
    entity_category: diagnostic

  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} Compressor Running"
    register_type: discrete_input
    address: 17
    device_class: running

  # --- E CODES (General Errors) ---
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} E1 High Pressure"
    register_type: discrete_input
    address: 49
    device_class: problem
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} E2 Low Pressure"
    register_type: discrete_input
    address: 50
    device_class: problem
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} E3 No Water"
    register_type: discrete_input
    address: 51
    device_class: problem
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} E6 Low Water Flow"
    register_type: discrete_input
    address: 54
    device_class: problem
    entity_category: diagnostic

  # --- P CODES (Sensor Failures) ---
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} P1 Water Inlet Sensor"
    register_type: discrete_input
    address: 65
    device_class: problem
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} P2 Water Outlet Sensor"
    register_type: discrete_input
    address: 66
    device_class: problem
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} P7 Ambient Temp Sensor"
    register_type: discrete_input
    address: 71
    device_class: problem
    entity_category: diagnostic

  # --- F CODES (Inverter/Drive Failures) ---
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} F1 Compressor Drive"
    register_type: discrete_input
    address: 81
    device_class: problem
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} F4 Compressor Running"
    register_type: discrete_input
    address: 84
    device_class: problem
    entity_category: diagnostic
  - platform: modbus_controller
    modbus_controller_id: heatpump
    name: "${name_prefix} F9 Fan Motor"
    register_type: discrete_input
    address: 89
    device_class: problem
    entity_category: diagnostic
